spring.application.name=spring_ai
server.port=8181


spring.ai.openai.api-key=${OPENAI_API_KEY}
# By default its uses gpt-3 model. We can ask model itself without setting below properties. 
spring.ai.openai.chat.options.model=gpt-4o-mini 
spring.ai.openai.chat.options.temperature=0.2