spring.application.name=spring_ai
server.port=8181


spring.ai.openai.api-key=${OPENAI_API_KEY}
# By default its uses gpt-3 model. We can ask model itself without setting below properties. 
# spring.ai.openai.chat.options.model=gpt-3
spring.ai.openai.chat.options.temperature=0.2

# Disable the auto bean of chat client. 
# spring.ai.chat.client.enabled=false

# Default Ollama connection (usually http://localhost:11434)
spring.ai.ollama.base-url=http://localhost:11434

# Specify the model (e.g., llama3, mistral, gemma, qwen2:0.5b)
spring.ai.ollama.chat.options.model=qwen2:0.5b

# Optional: Auto-pull model if missing
spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.format=json